language: csharp
solution: GSB_gestion_cloture.sln
mono: 
  - latest
script:
  - cd GSB_gestion_cloture
  - bash assets/post_install.sh
  - php assets/fonction.php
  - dotnet restore
  - msbuild
  - dotnet test test/TestsGsbGestionClotureTests1.dll



